# Original Data - Dictionary with Key as String and value is List of 2D array


In [1]:
import numpy as np

a = {'m':
     [((11,12,13),(14,15,16),(17, 18, 19)),    
      ((111,112,113),(114,115,116),(117, 118, 119))            
     ],
     
     'n':
     [((21,22,23),(24,25,26), (27, 28, 29)),    
      ((221,222,223),(224,225,226), (227, 228, 229))     
     ]}

In [2]:
a

{'m': [((11, 12, 13), (14, 15, 16), (17, 18, 19)),
  ((111, 112, 113), (114, 115, 116), (117, 118, 119))],
 'n': [((21, 22, 23), (24, 25, 26), (27, 28, 29)),
  ((221, 222, 223), (224, 225, 226), (227, 228, 229))]}

# Flattening Data


In [3]:
a['m']

[((11, 12, 13), (14, 15, 16), (17, 18, 19)),
 ((111, 112, 113), (114, 115, 116), (117, 118, 119))]

In [4]:
b = list(a.values())

In [5]:
c = np.array(b)

In [6]:
c

array([[[[ 11,  12,  13],
         [ 14,  15,  16],
         [ 17,  18,  19]],

        [[111, 112, 113],
         [114, 115, 116],
         [117, 118, 119]]],


       [[[ 21,  22,  23],
         [ 24,  25,  26],
         [ 27,  28,  29]],

        [[221, 222, 223],
         [224, 225, 226],
         [227, 228, 229]]]])

In [7]:
c[0]

array([[[ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19]],

       [[111, 112, 113],
        [114, 115, 116],
        [117, 118, 119]]])

In [8]:
c[0][0]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [9]:
c[0][0][0]

array([11, 12, 13])

In [10]:
c[0][0][0][0]

11

In [11]:
d = c.reshape([c.shape[0], c.shape[1], c.shape[2] * c.shape[3]])
d

array([[[ 11,  12,  13,  14,  15,  16,  17,  18,  19],
        [111, 112, 113, 114, 115, 116, 117, 118, 119]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29],
        [221, 222, 223, 224, 225, 226, 227, 228, 229]]])

# End result

In [12]:
key_count = 0
final_list = []
keys = {'m':1, 'n':2}
for d1 in d:
    for d2 in d1:
        d2 = list(d2)
        d2.append(keys[a.keys()[key_count]])
        final_list.append(d2)
    key_count = key_count + 1
final_list = np.array(final_list)

In [13]:
final_list

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,   1],
       [111, 112, 113, 114, 115, 116, 117, 118, 119,   1],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,   2],
       [221, 222, 223, 224, 225, 226, 227, 228, 229,   2]])